import { Tile } from '../tile'

export const level2: Tile[][] = [
  [
    { tileType: 'HM' },
    { tileType: 'HS' },
    { tileType: 'RT' },
    { tileType: 'RS' },
    { tileType: 'RT' },
    { tileType: 'HL' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HS' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [0] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [90] },
    { tileType: 'HL' },
    { tileType: 'HM' }
  ],
  [
    { tileType: 'HL' },
    { tileType: 'RT' },
    { tileType: 'RT' },
    { tileType: 'HM' },
    { tileType: 'RT' },
    { tileType: 'RS' },
    { tileType: 'R4W', partOfWinningPath: true, validRotations: [0, 90, 180, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [180] },
    { tileType: 'HL' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HL' },
    { tileType: 'HL' }
  ],
  [
    { tileType: 'RT' },
    { tileType: 'RT' },
    { tileType: 'HL' },
    { tileType: 'HS' },
    { tileType: 'HS' },
    { tileType: 'HM' },
    { tileType: 'RS' },
    { tileType: 'HL' },
    { tileType: 'HL' },
    { tileType: 'HM' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [90] }
  ],
  [
    { tileType: 'RS' },
    { tileType: 'HS' },
    { tileType: 'HM' },
    { tileType: 'RT' },
    { tileType: 'RS' },
    { tileType: 'RS' },
    { tileType: 'RT' },
    { tileType: 'OS' },
    { tileType: 'OL' },
    { tileType: 'OM' },
    { tileType: 'HS' },
    { tileType: 'HM' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] }
  ],
  [
    { tileType: 'RT' },
    { tileType: 'RS' },
    { tileType: 'R3W' },
    { tileType: 'R3W' },
    { tileType: 'OM' },
    { tileType: 'OM' },
    { tileType: 'OS' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [0] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [90] },
    { tileType: 'HS' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [0] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [180] }
  ],
  [
    { tileType: 'HL' },
    { tileType: 'HL' },
    { tileType: 'RT' },
    { tileType: 'RT' },
    { tileType: 'OL' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [0] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [180] },
    { tileType: 'OS' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HS' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HS' }
  ],
  [
    { tileType: 'HM' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [0] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [180] },
    { tileType: 'OS' },
    { tileType: 'RS' },
    { tileType: 'OM' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HS' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HM' }
  ],
  [
    { tileType: 'RT', partOfWinningPath: true, validRotations: [0] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [180] },
    { tileType: 'HM' },
    { tileType: 'OM' },
    { tileType: 'OM' },
    { tileType: 'OL' },
    { tileType: 'OM' },
    { tileType: 'RS' },
    { tileType: 'OL' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HL' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HL' }
  ],
  [
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HM' },
    { tileType: 'RS' },
    { tileType: 'OL' },
    { tileType: 'RT' },
    { tileType: 'RS' },
    { tileType: 'RS' },
    { tileType: 'RT' },
    { tileType: 'OM' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [180] },
    { tileType: 'HS' }
  ],
  [
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HL' },
    { tileType: 'RS' },
    { tileType: 'OM' },
    { tileType: 'RT' },
    { tileType: 'RS' },
    { tileType: 'RT' },
    { tileType: 'OS' },
    { tileType: 'OS' },
    { tileType: 'OM' },
    { tileType: 'HS' },
    { tileType: 'RS' },
    { tileType: 'HM' }
  ],
  [
    { tileType: 'RT', partOfWinningPath: true, validRotations: [270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'R3W', partOfWinningPath: true, validRotations: [0, 90] },
    { tileType: 'HS' },
    { tileType: 'HS' },
    { tileType: 'HS' },
    { tileType: 'RS' },
    { tileType: 'HS' },
    { tileType: 'RT' },
    { tileType: 'RT' },
    { tileType: 'HL' },
    { tileType: 'RS' },
    { tileType: 'HS' }
  ],
  [
    { tileType: 'HL' },
    { tileType: 'HS' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HS' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [0] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'R4W', partOfWinningPath: true, validRotations: [0, 90, 180, 270] },
    { tileType: 'RS' },
    { tileType: 'R3W' },
    { tileType: 'R3W' },
    { tileType: 'RS' },
    { tileType: 'R3W' },
    { tileType: 'HL' }
  ],
  [
    { tileType: 'HM' },
    { tileType: 'HS' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [180] },
    { tileType: 'HL' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HM' },
    { tileType: 'RT' },
    { tileType: 'RT' },
    { tileType: 'HS' },
    { tileType: 'RS' },
    { tileType: 'HS' }
  ]
] as Tile[][]
