import { Tile } from '../tile'

export const level3: Tile[][] = [
  [
    { tileType: 'HL' },
    { tileType: 'HL' },
    { tileType: 'RT' },
    { tileType: 'RS' },
    { tileType: 'RT' },
    { tileType: 'HL' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HS' },
    { tileType: 'HL' },
    { tileType: 'HM' },
    { tileType: 'HL' },
    { tileType: 'HS' },
    { tileType: 'HL' }
  ],
  [
    { tileType: 'HM' },
    { tileType: 'RT' },
    { tileType: 'RT' },
    { tileType: 'HS' },
    { tileType: 'RT' },
    { tileType: 'RS' },
    { tileType: 'R3W', partOfWinningPath: true, validRotations: [180, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [90] },
    { tileType: 'HM' },
    { tileType: 'RT' },
    { tileType: 'RS' },
    { tileType: 'RT' }
  ],
  [
    { tileType: 'HM' },
    { tileType: 'RS' },
    { tileType: 'HM' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [0] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [90] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HM' },
    { tileType: 'RS' },
    { tileType: 'HS' },
    { tileType: 'RS' }
  ],
  [
    { tileType: 'RT' },
    { tileType: 'R3W' },
    { tileType: 'HL' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [0] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [90] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'OL' },
    { tileType: 'RT' },
    { tileType: 'R3W' },
    { tileType: 'RT' }
  ],
  [
    { tileType: 'RS' },
    { tileType: 'RS' },
    { tileType: 'HL' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [0] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [180] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'OS' },
    { tileType: 'HM' },
    { tileType: 'RS' },
    { tileType: 'HL' }
  ],
  [
    { tileType: 'RT' },
    { tileType: 'R3W' },
    { tileType: 'HM' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [180] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'OL' },
    { tileType: 'RT' },
    { tileType: 'RT' },
    { tileType: 'HL' }
  ],
  [
    { tileType: 'HS' },
    { tileType: 'RS' },
    { tileType: 'HM' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [180] },
    { tileType: 'OS' },
    { tileType: 'RS' },
    { tileType: 'HL' },
    { tileType: 'HS' }
  ],
  [
    { tileType: 'HL' },
    { tileType: 'HL' },
    { tileType: 'HL' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'R3W', partOfWinningPath: true, validRotations: [0, 90] },
    { tileType: 'HL' },
    { tileType: 'HL' }
  ],
  [
    { tileType: 'HL' },
    { tileType: 'RS' },
    { tileType: 'HL' },
    { tileType: 'OS' },
    { tileType: 'OL' },
    { tileType: 'OL' },
    { tileType: 'OL' },
    { tileType: 'OM' },
    { tileType: 'OS' },
    { tileType: 'OL' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [270] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [90] }
  ],
  [
    { tileType: 'RT' },
    { tileType: 'R3W' },
    { tileType: 'RT' },
    { tileType: 'OS' },
    { tileType: 'RS' },
    { tileType: 'OL' },
    { tileType: 'OS' },
    { tileType: 'RT' },
    { tileType: 'RS' },
    { tileType: 'OM' },
    { tileType: 'HM' },
    { tileType: 'HL' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] }
  ],
  [
    { tileType: 'RS' },
    { tileType: 'HM' },
    { tileType: 'R3W' },
    { tileType: 'RS' },
    { tileType: 'R3W' },
    { tileType: 'HM' },
    { tileType: 'HS' },
    { tileType: 'RS' },
    { tileType: 'HL' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [0] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [90] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] }
  ],
  [
    { tileType: 'RT' },
    { tileType: 'RS' },
    { tileType: 'RT' },
    { tileType: 'HL' },
    { tileType: 'RT' },
    { tileType: 'RS' },
    { tileType: 'R3W', partOfWinningPath: true, validRotations: [0, 270] },
    { tileType: 'R3W', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [90, 270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [180] },
    { tileType: 'HS' },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [270] },
    { tileType: 'RT', partOfWinningPath: true, validRotations: [180] }
  ],
  [
    { tileType: 'HM' },
    { tileType: 'HL' },
    { tileType: 'HL' },
    { tileType: 'HM' },
    { tileType: 'HS' },
    { tileType: 'HS' },
    { tileType: 'RS', partOfWinningPath: true, validRotations: [0, 180] },
    { tileType: 'HS' },
    { tileType: 'HL' },
    { tileType: 'HM' },
    { tileType: 'HS' },
    { tileType: 'HS' },
    { tileType: 'HS' }
  ]
] as Tile[][]
